name: auto-release

on:
  push:
    branches:
    - master

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses:  cloudposse/github-actions-workflows/.github/workflows/controller-release.yml@main

