name: auto-release

on:
  push:
    branches:
    - master

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses:  cloudposse/.github/.github/workflows/shared-auto-release.yml@main

